<?php
/***************************************************************
 *  Copyright notice
 *
 *  (c) 2010 Xavier Perseguers <typo3@perseguers.ch>
 *  All rights reserved
 *
 *  This script is part of the TYPO3 project. The TYPO3 project is
 *  free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  The GNU General Public License can be found at
 *  http://www.gnu.org/copyleft/gpl.html.
 *  A copy is found in the textfile GPL.txt and important notices to the license
 *  from the author is found in LICENSE.txt distributed with these scripts.
 *
 *
 *  This script is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  This copyright notice MUST APPEAR in all copies of the script!
 ***************************************************************/


/**
 * This interface contains all classes of lexemes.
 *
 * @category    Parser
 * @package     TYPO3
 * @subpackage  tx_dbal\sql
 * @author      Xavier Perseguers <typo3@perseguers.ch>
 * @copyright   Copyright 2010
 * @license     http://www.gnu.org/copyleft/gpl.html
 * @version     SVN: $Id$
 */
interface tx_dbal_sql_Tokens {

	const EOF                             =  -1; // end of file
    const BAD                             =   0; // unknown lexeme

    const T_IDENT                         =   1; // identifier
    const T_NUMBER                        =   2; // number
    const T_STRING                        =   3; // string

    const T_LPAREN                        =   4; // '('
    const T_RPAREN                        =   5; // ')'
	const T_COMMA                         =   6; // ','
	const T_SEMICOLON                     =   7; // ';'
	const T_QUESTION                      =   8; // '?'

	// Operators
	// see http://dev.mysql.com/doc/refman/5.5/en/expressions.html
	const T_PLUS                          =   9; // '+'
	const T_MINUS                         =  10; // '-'
	const T_DIVIDE                        =  11; // '/'
	const T_STAR                          =  12; // '*'
	const T_MODULO                        =  13; // '%'
	const T_POW                           =  14; // '^'
	const T_EQUAL                         =  15; // '='
	const T_GREATEREQUAL                  =  16; // '>='
	const T_GREATER                       =  17; // '>'
	const T_LESSEQUAL                     =  18; // '<='
	const T_LESS                          =  19; // '<'
	const T_BOX                           =  20; // '<>'
	const T_NOTEQUAL                      =  21; // '!='
	const T_LOGICNOT                      =  22; // '!'
	const T_LOGICAND                      =  23; // '&&'
	const T_LOGICOR                       =  24; // '||'
	const T_BITAND                        =  25; // '&'
	const T_BITOR                         =  26; // '|'

	// Functions
	const T_CONCAT                        =  40; // 'CONCAT'
	const T_FINDINSET                     =  41; // 'FIND_IN_SET'

	// Reserved words
	// see http://dev.mysql.com/doc/mysqld-version-reference/en/mysqld-version-reference-reservedwords-5-5.html
	const T_ACCESSIBLE                    = 100; // 'ACCESSIBLE'
	const T_ADD                           = 101; // 'ADD'
	const T_ALL                           = 102; // 'ALL'
	const T_ALTER                         = 103; // 'ALTER'
	const T_ANALYZE                       = 104; // 'ANALYZE'
	const T_AND                           = 105; // 'AND'
	const T_AS                            = 106; // 'AS'
	const T_ASC                           = 107; // 'ASC'
	const T_ASENSITIVE                    = 108; // 'ASENSITIVE'
	const T_BEFORE                        = 109; // 'BEFORE'
	const T_BETWEEN                       = 110; // 'BETWEEN'
	const T_BIGINT                        = 111; // 'BIGINT'
	const T_BINARY                        = 112; // 'BINARY'
	const T_BLOB                          = 113; // 'BLOB'
	const T_BOTH                          = 114; // 'BOTH'
	const T_BY                            = 115; // 'BY'
	const T_CALL                          = 116; // 'CALL'
	const T_CASCADE                       = 117; // 'CASCADE'
	const T_CASE                          = 118; // 'CASE'
	const T_CHANGE                        = 119; // 'CHANGE'
	const T_CHAR                          = 120; // 'CHAR'
	const T_CHARACTER                     = 121; // 'CHARACTER'
	const T_CHECK                         = 122; // 'CHECK'
	const T_COLLATE                       = 123; // 'COLLATE'
	const T_COLUMN                        = 124; // 'COLUMN'
	const T_CONDITION                     = 125; // 'CONDITION'
	const T_CONSTRAINT                    = 126; // 'CONSTRAINT'
	const T_CONTINUE                      = 127; // 'CONTINUE'
	const T_CONVERT                       = 128; // 'CONVERT'
	const T_CREATE                        = 129; // 'CREATE'
	const T_CROSS                         = 130; // 'CROSS'
	const T_CURRENT_DATE                  = 131; // 'CURRENT_DATE'
	const T_CURRENT_TIME                  = 132; // 'CURRENT_TIME'
	const T_CURRENT_TIMESTAMP             = 133; // 'CURRENT_TIMESTAMP'
	const T_CURRENT_USER                  = 134; // 'CURRENT_USER'
	const T_CURSOR                        = 135; // 'CURSOR'
	const T_DATABASE                      = 136; // 'DATABASE'
	const T_DATABASES                     = 137; // 'DATABASES'
	const T_DAY_HOUR                      = 138; // 'DAY_HOUR'
	const T_DAY_MICROSECOND               = 139; // 'DAY_MICROSECOND'
	const T_DAY_MINUTE                    = 140; // 'DAY_MINUTE'
	const T_DAY_SECOND                    = 141; // 'DAY_SECOND'
	const T_DEC                           = 142; // 'DEC'
	const T_DECIMAL                       = 143; // 'DECIMAL'
	const T_DECLARE                       = 144; // 'DECLARE'
	const T_DEFAULT                       = 145; // 'DEFAULT'
	const T_DELAYED                       = 146; // 'DELAYED'
	const T_DELETE                        = 147; // 'DELETE'
	const T_DESC                          = 148; // 'DESC'
	const T_DESCRIBE                      = 149; // 'DESCRIBE'
	const T_DETERMINISTIC                 = 150; // 'DETERMINISTIC'
	const T_DISTINCT                      = 151; // 'DISTINCT'
	const T_DISTINCTROW                   = 152; // 'DISTINCTROW'
	const T_DIV                           = 153; // 'DIV'
	const T_DOUBLE                        = 154; // 'DOUBLE'
	const T_DROP                          = 155; // 'DROP'
	const T_DUAL                          = 156; // 'DUAL'
	const T_EACH                          = 157; // 'EACH'
	const T_ELSE                          = 158; // 'ELSE'
	const T_ELSEIF                        = 159; // 'ELSEIF'
	const T_ENCLOSED                      = 160; // 'ENCLOSED'
	const T_ESCAPED                       = 161; // 'ESCAPED'
	const T_EXISTS                        = 162; // 'EXISTS'
	const T_EXIT                          = 163; // 'EXIT'
	const T_EXPLAIN                       = 164; // 'EXPLAIN'
	const T_FALSE                         = 165; // 'FALSE'
	const T_FETCH                         = 166; // 'FETCH'
	const T_FLOAT                         = 167; // 'FLOAT'
	const T_FLOAT4                        = 168; // 'FLOAT4'
	const T_FLOAT8                        = 169; // 'FLOAT8'
	const T_FOR                           = 170; // 'FOR'
	const T_FORCE                         = 171; // 'FORCE'
	const T_FOREIGN                       = 172; // 'FOREIGN'
	const T_FROM                          = 173; // 'FROM'
	const T_FULLTEXT                      = 174; // 'FULLTEXT'
	const T_GENERAL                       = 175; // 'GENERAL'
	const T_GRANT                         = 176; // 'GRANT'
	const T_GROUP                         = 177; // 'GROUP'
	const T_HAVING                        = 178; // 'HAVING'
	const T_HIGH_PRIORITY                 = 179; // 'HIGH_PRIORITY'
	const T_HOUR_MICROSECOND              = 180; // 'HOUR_MICROSECOND'
	const T_HOUR_MINUTE                   = 181; // 'HOUR_MINUTE'
	const T_HOUR_SECOND                   = 182; // 'HOUR_SECOND'
	const T_IF                            = 183; // 'IF'
	const T_IGNORE                        = 184; // 'IGNORE'
	const T_IGNORE_SERVER_IDS             = 185; // 'IGNORE_SERVER_IDS'
	const T_IN                            = 186; // 'IN'
	const T_INDEX                         = 187; // 'INDEX'
	const T_INFILE                        = 188; // 'INFILE'
	const T_INNER                         = 189; // 'INNER'
	const T_INOUT                         = 190; // 'INOUT'
	const T_INSENSITIVE                   = 191; // 'INSENSITIVE'
	const T_INSERT                        = 192; // 'INSERT'
	const T_INT                           = 193; // 'INT'
	const T_INT1                          = 194; // 'INT1'
	const T_INT2                          = 195; // 'INT2'
	const T_INT3                          = 196; // 'INT3'
	const T_INT4                          = 197; // 'INT4'
	const T_INT8                          = 198; // 'INT8'
	const T_INTEGER                       = 199; // 'INTEGER'
	const T_INTERVAL                      = 200; // 'INTERVAL'
	const T_INTO                          = 201; // 'INTO'
	const T_IS                            = 202; // 'IS'
	const T_ITERATE                       = 203; // 'ITERATE'
	const T_JOIN                          = 204; // 'JOIN'
	const T_KEY                           = 205; // 'KEY'
	const T_KEYS                          = 206; // 'KEYS'
	const T_KILL                          = 207; // 'KILL'
	const T_LEADING                       = 208; // 'LEADING'
	const T_LEAVE                         = 209; // 'LEAVE'
	const T_LEFT                          = 210; // 'LEFT'
	const T_LIKE                          = 211; // 'LIKE'
	const T_LIMIT                         = 212; // 'LIMIT'
	const T_LINEAR                        = 213; // 'LINEAR'
	const T_LINES                         = 214; // 'LINES'
	const T_LOAD                          = 215; // 'LOAD'
	const T_LOCALTIME                     = 216; // 'LOCALTIME'
	const T_LOCALTIMESTAMP                = 217; // 'LOCALTIMESTAMP'
	const T_LOCK                          = 218; // 'LOCK'
	const T_LONG                          = 219; // 'LONG'
	const T_LONGBLOB                      = 220; // 'LONGBLOB'
	const T_LONGTEXT                      = 221; // 'LONGTEXT'
	const T_LOOP                          = 222; // 'LOOP'
	const T_LOW_PRIORITY                  = 223; // 'LOW_PRIORITY'
	const T_MASTER_HEARTBEAT_PERIOD       = 224; // 'MASTER_HEARTBEAT_PERIOD'
	const T_MASTER_SSL_VERIFY_SERVER_CERT = 225; // 'MASTER_SSL_VERIFY_SERVER_CERT'
	const T_MATCH                         = 226; // 'MATCH'
	const T_MAXVALUE                      = 227; // 'MAXVALUE'
	const T_MEDIUMBLOB                    = 228; // 'MEDIUMBLOB'
	const T_MEDIUMINT                     = 229; // 'MEDIUMINT'
	const T_MEDIUMTEXT                    = 230; // 'MEDIUMTEXT'
	const T_MIDDLEINT                     = 231; // 'MIDDLEINT'
	const T_MINUTE_MICROSECOND            = 232; // 'MINUTE_MICROSECOND'
	const T_MINUTE_SECOND                 = 233; // 'MINUTE_SECOND'
	const T_MOD                           = 234; // 'MOD'
	const T_MODIFIES                      = 235; // 'MODIFIES'
	const T_NATURAL                       = 236; // 'NATURAL'
	const T_NOT                           = 237; // 'NOT'
	const T_NO_WRITE_TO_BINLOG            = 238; // 'NO_WRITE_TO_BINLOG'
	const T_NULL                          = 239; // 'NULL'
	const T_NUMERIC                       = 240; // 'NUMERIC'
	const T_ON                            = 241; // 'ON'
	const T_OPTIMIZE                      = 242; // 'OPTIMIZE'
	const T_OPTION                        = 243; // 'OPTION'
	const T_OPTIONALLY                    = 244; // 'OPTIONALLY'
	const T_OR                            = 245; // 'OR'
	const T_ORDER                         = 246; // 'ORDER'
	const T_OUT                           = 247; // 'OUT'
	const T_OUTER                         = 248; // 'OUTER'
	const T_OUTFILE                       = 249; // 'OUTFILE'
	const T_PRECISION                     = 250; // 'PRECISION'
	const T_PRIMARY                       = 251; // 'PRIMARY'
	const T_PROCEDURE                     = 252; // 'PROCEDURE'
	const T_PURGE                         = 253; // 'PURGE'
	const T_RANGE                         = 254; // 'RANGE'
	const T_READ                          = 255; // 'READ'
	const T_READS                         = 256; // 'READS'
	const T_READ_WRITE                    = 257; // 'READ_WRITE'
	const T_REAL                          = 258; // 'REAL'
	const T_REFERENCES                    = 259; // 'REFERENCES'
	const T_REGEXP                        = 260; // 'REGEXP'
	const T_RELEASE                       = 261; // 'RELEASE'
	const T_RENAME                        = 262; // 'RENAME'
	const T_REPEAT                        = 263; // 'REPEAT'
	const T_REPLACE                       = 264; // 'REPLACE'
	const T_REQUIRE                       = 265; // 'REQUIRE'
	const T_RESIGNAL                      = 266; // 'RESIGNAL'
	const T_RESTRICT                      = 267; // 'RESTRICT'
	const T_RETURN                        = 268; // 'RETURN'
	const T_REVOKE                        = 269; // 'REVOKE'
	const T_RIGHT                         = 260; // 'RIGHT'
	const T_RLIKE                         = 271; // 'RLIKE'
	const T_SCHEMA                        = 272; // 'SCHEMA'
	const T_SCHEMAS                       = 273; // 'SCHEMAS'
	const T_SECOND_MICROSECOND            = 274; // 'SECOND_MICROSECOND'
	const T_SELECT                        = 275; // 'SELECT'
	const T_SENSITIVE                     = 276; // 'SENSITIVE'
	const T_SEPARATOR                     = 277; // 'SEPARATOR'
	const T_SET                           = 278; // 'SET'
	const T_SHOW                          = 279; // 'SHOW'
	const T_SIGNAL                        = 280; // 'SIGNAL'
	const T_SLOW                          = 281; // 'SLOW'
	const T_SMALLINT                      = 282; // 'SMALLINT'
	const T_SPATIAL                       = 283; // 'SPATIAL'
	const T_SPECIFIC                      = 284; // 'SPECIFIC'
	const T_SQL                           = 285; // 'SQL'
	const T_SQLEXCEPTION                  = 286; // 'SQLEXCEPTION'
	const T_SQLSTATE                      = 287; // 'SQLSTATE'
	const T_SQLWARNING                    = 288; // 'SQLWARNING'
	const T_SQL_BIG_RESULT                = 289; // 'SQL_BIG_RESULT'
	const T_SQL_CALC_FOUND_ROWS           = 290; // 'SQL_CALC_FOUND_ROWS'
	const T_SQL_SMALL_RESULT              = 291; // 'SQL_SMALL_RESULT'
	const T_SSL                           = 292; // 'SSL'
	const T_STARTING                      = 293; // 'STARTING'
	const T_STRAIGHT_JOIN                 = 294; // 'STRAIGHT_JOIN'
	const T_TABLE                         = 295; // 'TABLE'
	const T_TERMINATED                    = 296; // 'TERMINATED'
	const T_THEN                          = 297; // 'THEN'
	const T_TINYBLOB                      = 298; // 'TINYBLOB'
	const T_TINYINT                       = 299; // 'TINYINT'
	const T_TINYTEXT                      = 300; // 'TINYTEXT'
	const T_TO                            = 301; // 'TO'
	const T_TRAILING                      = 302; // 'TRAILING'
	const T_TRIGGER                       = 303; // 'TRIGGER'
	const T_TRUE                          = 304; // 'TRUE'
	const T_UNDO                          = 305; // 'UNDO'
	const T_UNION                         = 306; // 'UNION'
	const T_UNIQUE                        = 307; // 'UNIQUE'
	const T_UNLOCK                        = 308; // 'UNLOCK'
	const T_UNSIGNED                      = 309; // 'UNSIGNED'
	const T_UPDATE                        = 310; // 'UPDATE'
	const T_USAGE                         = 311; // 'USAGE'
	const T_USE                           = 312; // 'USE'
	const T_USING                         = 313; // 'USING'
	const T_UTC_DATE                      = 314; // 'UTC_DATE'
	const T_UTC_TIME                      = 315; // 'UTC_TIME'
	const T_UTC_TIMESTAMP                 = 316; // 'UTC_TIMESTAMP'
	const T_VALUES                        = 317; // 'VALUES'
	const T_VARBINARY                     = 318; // 'VARBINARY'
	const T_VARCHAR                       = 319; // 'VARCHAR'
	const T_VARCHARACTER                  = 320; // 'VARCHARACTER'
	const T_VARYING                       = 321; // 'VARYING'
	const T_WHEN                          = 322; // 'WHEN'
	const T_WHERE                         = 323; // 'WHERE'
	const T_WHILE                         = 324; // 'WHILE'
	const T_WITH                          = 325; // 'WITH'
	const T_WRITE                         = 326; // 'WRITE'
	const T_XOR                           = 327; // 'XOR'
	const T_YEAR_MONTH                    = 328; // 'YEAR_MONTH'
	const T_ZEROFILL                      = 329; // 'ZEROFILL'

}

?>