<?php
/***************************************************************
 *  Copyright notice
 *
 *  (c) 2010 Xavier Perseguers <typo3@perseguers.ch>
 *  All rights reserved
 *
 *  This script is part of the TYPO3 project. The TYPO3 project is
 *  free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  The GNU General Public License can be found at
 *  http://www.gnu.org/copyleft/gpl.html.
 *  A copy is found in the textfile GPL.txt and important notices to the license
 *  from the author is found in LICENSE.txt distributed with these scripts.
 *
 *
 *  This script is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  This copyright notice MUST APPEAR in all copies of the script!
 ***************************************************************/


/**
 * This interface contains all classes of lexemes.
 *
 * $Id$
 *
 * @author Xavier Perseguers <typo3@perseguers.ch>
 * @package TYPO3
 * @subpackage dbal\sql
 */
interface tx_dbal_sql_Tokens {

	const EOF                             =  -1; // end of file
    const BAD                             =   0; // unknown lexeme

    const T_IDENT                         =   1; // identifier
    const T_NUMBER                        =   2; // number
    const T_STRING                        =   3; // string

    const T_LPAREN                        =   4; // '('
    const T_RPAREN                        =   5; // ')'
	const T_COMMA                         =   6; // ','
	const T_SEMICOLON                     =   7; // ';'
	const T_QUESTION                      =   8; // '?'

	// Operators
	// see http://dev.mysql.com/doc/refman/5.5/en/expressions.html
	const T_PLUS                          =   9; // '+'
	const T_MINUS                         =  10; // '-'
	const T_DIVIDE                        =  11; // '/'
	const T_STAR                          =  12; // '*'
	const T_MODULO                        =  13; // '%'
	const T_POW                           =  14; // '^'
	const T_EQUAL                         =  15; // '='
	const T_GREATEREQUAL                  =  16; // '>='
	const T_GREATER                       =  17; // '>'
	const T_LESSEQUAL                     =  18; // '<='
	const T_LESS                          =  19; // '<'
	const T_BOX                           =  20; // '<>'
	const T_NOTEQUAL                      =  21; // '!='
	const T_LOGICNOT                      =  22; // '!'
	const T_LOGICAND                      =  23; // '&&'
	const T_LOGICOR                       =  24; // '||'
	const T_BITAND                        =  25; // '&'
	const T_BITOR                         =  26; // '|'

	// Reserved words
	// see http://dev.mysql.com/doc/mysqld-version-reference/en/mysqld-version-reference-reservedwords-5-5.html
	const T_ACCESSIBLE                    =  40; // 'ACCESSIBLE'
	const T_ADD                           =  41; // 'ADD'
	const T_ALL                           =  42; // 'ALL'
	const T_ALTER                         =  43; // 'ALTER'
	const T_ANALYZE                       =  44; // 'ANALYZE'
	const T_AND                           =  45; // 'AND'
	const T_AS                            =  46; // 'AS'
	const T_ASC                           =  47; // 'ASC'
	const T_ASENSITIVE                    =  48; // 'ASENSITIVE'
	const T_BEFORE                        =  49; // 'BEFORE'
	const T_BETWEEN                       =  50; // 'BETWEEN'
	const T_BIGINT                        =  51; // 'BIGINT'
	const T_BINARY                        =  52; // 'BINARY'
	const T_BLOB                          =  53; // 'BLOB'
	const T_BOTH                          =  54; // 'BOTH'
	const T_BY                            =  55; // 'BY'
	const T_CALL                          =  56; // 'CALL'
	const T_CASCADE                       =  57; // 'CASCADE'
	const T_CASE                          =  58; // 'CASE'
	const T_CHANGE                        =  59; // 'CHANGE'
	const T_CHAR                          =  60; // 'CHAR'
	const T_CHARACTER                     =  61; // 'CHARACTER'
	const T_CHECK                         =  62; // 'CHECK'
	const T_COLLATE                       =  63; // 'COLLATE'
	const T_COLUMN                        =  64; // 'COLUMN'
	const T_CONDITION                     =  65; // 'CONDITION'
	const T_CONSTRAINT                    =  66; // 'CONSTRAINT'
	const T_CONTINUE                      =  67; // 'CONTINUE'
	const T_CONVERT                       =  68; // 'CONVERT'
	const T_CREATE                        =  69; // 'CREATE'
	const T_CROSS                         =  70; // 'CROSS'
	const T_CURRENT_DATE                  =  71; // 'CURRENT_DATE'
	const T_CURRENT_TIME                  =  72; // 'CURRENT_TIME'
	const T_CURRENT_TIMESTAMP             =  73; // 'CURRENT_TIMESTAMP'
	const T_CURRENT_USER                  =  74; // 'CURRENT_USER'
	const T_CURSOR                        =  75; // 'CURSOR'
	const T_DATABASE                      =  76; // 'DATABASE'
	const T_DATABASES                     =  77; // 'DATABASES'
	const T_DAY_HOUR                      =  78; // 'DAY_HOUR'
	const T_DAY_MICROSECOND               =  79; // 'DAY_MICROSECOND'
	const T_DAY_MINUTE                    =  80; // 'DAY_MINUTE'
	const T_DAY_SECOND                    =  81; // 'DAY_SECOND'
	const T_DEC                           =  82; // 'DEC'
	const T_DECIMAL                       =  83; // 'DECIMAL'
	const T_DECLARE                       =  84; // 'DECLARE'
	const T_DEFAULT                       =  85; // 'DEFAULT'
	const T_DELAYED                       =  86; // 'DELAYED'
	const T_DELETE                        =  87; // 'DELETE'
	const T_DESC                          =  88; // 'DESC'
	const T_DESCRIBE                      =  89; // 'DESCRIBE'
	const T_DETERMINISTIC                 =  90; // 'DETERMINISTIC'
	const T_DISTINCT                      =  91; // 'DISTINCT'
	const T_DISTINCTROW                   =  92; // 'DISTINCTROW'
	const T_DIV                           =  93; // 'DIV'
	const T_DOUBLE                        =  94; // 'DOUBLE'
	const T_DROP                          =  95; // 'DROP'
	const T_DUAL                          =  96; // 'DUAL'
	const T_EACH                          =  97; // 'EACH'
	const T_ELSE                          =  98; // 'ELSE'
	const T_ELSEIF                        =  99; // 'ELSEIF'
	const T_ENCLOSED                      = 100; // 'ENCLOSED'
	const T_ESCAPED                       = 101; // 'ESCAPED'
	const T_EXISTS                        = 102; // 'EXISTS'
	const T_EXIT                          = 103; // 'EXIT'
	const T_EXPLAIN                       = 104; // 'EXPLAIN'
	const T_FALSE                         = 105; // 'FALSE'
	const T_FETCH                         = 106; // 'FETCH'
	const T_FLOAT                         = 107; // 'FLOAT'
	const T_FLOAT4                        = 108; // 'FLOAT4'
	const T_FLOAT8                        = 109; // 'FLOAT8'
	const T_FOR                           = 110; // 'FOR'
	const T_FORCE                         = 111; // 'FORCE'
	const T_FOREIGN                       = 112; // 'FOREIGN'
	const T_FROM                          = 113; // 'FROM'
	const T_FULLTEXT                      = 114; // 'FULLTEXT'
	const T_GENERAL                       = 115; // 'GENERAL'
	const T_GRANT                         = 116; // 'GRANT'
	const T_GROUP                         = 117; // 'GROUP'
	const T_HAVING                        = 118; // 'HAVING'
	const T_HIGH_PRIORITY                 = 119; // 'HIGH_PRIORITY'
	const T_HOUR_MICROSECOND              = 120; // 'HOUR_MICROSECOND'
	const T_HOUR_MINUTE                   = 121; // 'HOUR_MINUTE'
	const T_HOUR_SECOND                   = 122; // 'HOUR_SECOND'
	const T_IF                            = 123; // 'IF'
	const T_IGNORE                        = 124; // 'IGNORE'
	const T_IGNORE_SERVER_IDS             = 125; // 'IGNORE_SERVER_IDS'
	const T_IN                            = 126; // 'IN'
	const T_INDEX                         = 127; // 'INDEX'
	const T_INFILE                        = 128; // 'INFILE'
	const T_INNER                         = 129; // 'INNER'
	const T_INOUT                         = 130; // 'INOUT'
	const T_INSENSITIVE                   = 131; // 'INSENSITIVE'
	const T_INSERT                        = 132; // 'INSERT'
	const T_INT                           = 133; // 'INT'
	const T_INT1                          = 134; // 'INT1'
	const T_INT2                          = 135; // 'INT2'
	const T_INT3                          = 136; // 'INT3'
	const T_INT4                          = 137; // 'INT4'
	const T_INT8                          = 138; // 'INT8'
	const T_INTEGER                       = 139; // 'INTEGER'
	const T_INTERVAL                      = 140; // 'INTERVAL'
	const T_INTO                          = 141; // 'INTO'
	const T_IS                            = 142; // 'IS'
	const T_ITERATE                       = 143; // 'ITERATE'
	const T_JOIN                          = 144; // 'JOIN'
	const T_KEY                           = 145; // 'KEY'
	const T_KEYS                          = 146; // 'KEYS'
	const T_KILL                          = 147; // 'KILL'
	const T_LEADING                       = 148; // 'LEADING'
	const T_LEAVE                         = 149; // 'LEAVE'
	const T_LEFT                          = 150; // 'LEFT'
	const T_LIKE                          = 151; // 'LIKE'
	const T_LIMIT                         = 152; // 'LIMIT'
	const T_LINEAR                        = 153; // 'LINEAR'
	const T_LINES                         = 154; // 'LINES'
	const T_LOAD                          = 155; // 'LOAD'
	const T_LOCALTIME                     = 156; // 'LOCALTIME'
	const T_LOCALTIMESTAMP                = 157; // 'LOCALTIMESTAMP'
	const T_LOCK                          = 158; // 'LOCK'
	const T_LONG                          = 159; // 'LONG'
	const T_LONGBLOB                      = 160; // 'LONGBLOB'
	const T_LONGTEXT                      = 161; // 'LONGTEXT'
	const T_LOOP                          = 162; // 'LOOP'
	const T_LOW_PRIORITY                  = 163; // 'LOW_PRIORITY'
	const T_MASTER_HEARTBEAT_PERIOD       = 164; // 'MASTER_HEARTBEAT_PERIOD'
	const T_MASTER_SSL_VERIFY_SERVER_CERT = 165; // 'MASTER_SSL_VERIFY_SERVER_CERT'
	const T_MATCH                         = 166; // 'MATCH'
	const T_MAXVALUE                      = 167; // 'MAXVALUE'
	const T_MEDIUMBLOB                    = 168; // 'MEDIUMBLOB'
	const T_MEDIUMINT                     = 169; // 'MEDIUMINT'
	const T_MEDIUMTEXT                    = 170; // 'MEDIUMTEXT'
	const T_MIDDLEINT                     = 171; // 'MIDDLEINT'
	const T_MINUTE_MICROSECOND            = 172; // 'MINUTE_MICROSECOND'
	const T_MINUTE_SECOND                 = 173; // 'MINUTE_SECOND'
	const T_MOD                           = 174; // 'MOD'
	const T_MODIFIES                      = 175; // 'MODIFIES'
	const T_NATURAL                       = 176; // 'NATURAL'
	const T_NOT                           = 177; // 'NOT'
	const T_NO_WRITE_TO_BINLOG            = 178; // 'NO_WRITE_TO_BINLOG'
	const T_NULL                          = 179; // 'NULL'
	const T_NUMERIC                       = 180; // 'NUMERIC'
	const T_ON                            = 181; // 'ON'
	const T_OPTIMIZE                      = 182; // 'OPTIMIZE'
	const T_OPTION                        = 183; // 'OPTION'
	const T_OPTIONALLY                    = 184; // 'OPTIONALLY'
	const T_OR                            = 185; // 'OR'
	const T_ORDER                         = 186; // 'ORDER'
	const T_OUT                           = 187; // 'OUT'
	const T_OUTER                         = 188; // 'OUTER'
	const T_OUTFILE                       = 189; // 'OUTFILE'
	const T_PRECISION                     = 190; // 'PRECISION'
	const T_PRIMARY                       = 191; // 'PRIMARY'
	const T_PROCEDURE                     = 192; // 'PROCEDURE'
	const T_PURGE                         = 193; // 'PURGE'
	const T_RANGE                         = 194; // 'RANGE'
	const T_READ                          = 195; // 'READ'
	const T_READS                         = 196; // 'READS'
	const T_READ_WRITE                    = 197; // 'READ_WRITE'
	const T_REAL                          = 198; // 'REAL'
	const T_REFERENCES                    = 199; // 'REFERENCES'
	const T_REGEXP                        = 200; // 'REGEXP'
	const T_RELEASE                       = 201; // 'RELEASE'
	const T_RENAME                        = 202; // 'RENAME'
	const T_REPEAT                        = 203; // 'REPEAT'
	const T_REPLACE                       = 204; // 'REPLACE'
	const T_REQUIRE                       = 205; // 'REQUIRE'
	const T_RESIGNAL                      = 206; // 'RESIGNAL'
	const T_RESTRICT                      = 207; // 'RESTRICT'
	const T_RETURN                        = 208; // 'RETURN'
	const T_REVOKE                        = 209; // 'REVOKE'
	const T_RIGHT                         = 200; // 'RIGHT'
	const T_RLIKE                         = 211; // 'RLIKE'
	const T_SCHEMA                        = 212; // 'SCHEMA'
	const T_SCHEMAS                       = 213; // 'SCHEMAS'
	const T_SECOND_MICROSECOND            = 214; // 'SECOND_MICROSECOND'
	const T_SELECT                        = 215; // 'SELECT'
	const T_SENSITIVE                     = 216; // 'SENSITIVE'
	const T_SEPARATOR                     = 217; // 'SEPARATOR'
	const T_SET                           = 218; // 'SET'
	const T_SHOW                          = 219; // 'SHOW'
	const T_SIGNAL                        = 220; // 'SIGNAL'
	const T_SLOW                          = 221; // 'SLOW'
	const T_SMALLINT                      = 222; // 'SMALLINT'
	const T_SPATIAL                       = 223; // 'SPATIAL'
	const T_SPECIFIC                      = 224; // 'SPECIFIC'
	const T_SQL                           = 225; // 'SQL'
	const T_SQLEXCEPTION                  = 226; // 'SQLEXCEPTION'
	const T_SQLSTATE                      = 227; // 'SQLSTATE'
	const T_SQLWARNING                    = 228; // 'SQLWARNING'
	const T_SQL_BIG_RESULT                = 229; // 'SQL_BIG_RESULT'
	const T_SQL_CALC_FOUND_ROWS           = 230; // 'SQL_CALC_FOUND_ROWS'
	const T_SQL_SMALL_RESULT              = 231; // 'SQL_SMALL_RESULT'
	const T_SSL                           = 232; // 'SSL'
	const T_STARTING                      = 233; // 'STARTING'
	const T_STRAIGHT_JOIN                 = 234; // 'STRAIGHT_JOIN'
	const T_TABLE                         = 235; // 'TABLE'
	const T_TERMINATED                    = 236; // 'TERMINATED'
	const T_THEN                          = 237; // 'THEN'
	const T_TINYBLOB                      = 238; // 'TINYBLOB'
	const T_TINYINT                       = 239; // 'TINYINT'
	const T_TINYTEXT                      = 240; // 'TINYTEXT'
	const T_TO                            = 241; // 'TO'
	const T_TRAILING                      = 242; // 'TRAILING'
	const T_TRIGGER                       = 243; // 'TRIGGER'
	const T_TRUE                          = 244; // 'TRUE'
	const T_UNDO                          = 245; // 'UNDO'
	const T_UNION                         = 246; // 'UNION'
	const T_UNIQUE                        = 247; // 'UNIQUE'
	const T_UNLOCK                        = 248; // 'UNLOCK'
	const T_UNSIGNED                      = 249; // 'UNSIGNED'
	const T_UPDATE                        = 250; // 'UPDATE'
	const T_USAGE                         = 251; // 'USAGE'
	const T_USE                           = 252; // 'USE'
	const T_USING                         = 253; // 'USING'
	const T_UTC_DATE                      = 254; // 'UTC_DATE'
	const T_UTC_TIME                      = 255; // 'UTC_TIME'
	const T_UTC_TIMESTAMP                 = 256; // 'UTC_TIMESTAMP'
	const T_VALUES                        = 257; // 'VALUES'
	const T_VARBINARY                     = 258; // 'VARBINARY'
	const T_VARCHAR                       = 259; // 'VARCHAR'
	const T_VARCHARACTER                  = 260; // 'VARCHARACTER'
	const T_VARYING                       = 261; // 'VARYING'
	const T_WHEN                          = 262; // 'WHEN'
	const T_WHERE                         = 263; // 'WHERE'
	const T_WHILE                         = 264; // 'WHILE'
	const T_WITH                          = 265; // 'WITH'
	const T_WRITE                         = 266; // 'WRITE'
	const T_XOR                           = 267; // 'XOR'
	const T_YEAR_MONTH                    = 268; // 'YEAR_MONTH'
	const T_ZEROFILL                      = 269; // 'ZEROFILL'

}

?>