<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2010-11-19 16:08


$extensionPath = t3lib_extMgm::extPath('dbal');
return array(
	'tx_dbal_driver_pdo' => $extensionPath . 'drivers/class.tx_dbal_driver_pdo.php',
	'tx_dbal_querycache' => $extensionPath . 'lib/class.tx_dbal_querycache.php',
	'tx_dbal_sqlengine' => $extensionPath . 'lib/class.tx_dbal_sqlengine.php',
	'ux_t3lib_sqlparser' => $extensionPath . 'class.ux_t3lib_sqlparser.php',
);
?>