<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2010-11-19 16:08


$extensionPath = t3lib_extMgm::extPath('dbal');
return array(
	'tx_dbal_sql_abstracttree' => $extensionPath . 'lib/sql/class.tx_dbal_sql_abstracttree.php',
	'tx_dbal_sql_error_tokenexpected' => $extensionPath . 'lib/sql/error/class.tx_dbal_sql_error_tokenexpected.php',
	'tx_dbal_sql_error_unknowntoken' => $extensionPath . 'lib/sql/error/class.tx_dbal_sql_error_unknowntoken.php',
	'tx_dbal_sql_global' => $extensionPath . 'lib/sql/class.tx_dbal_sql_global.php',
	'tx_dbal_sql_parser' => $extensionPath . 'lib/sql/class.tx_dbal_sql_parser.php',
	'tx_dbal_sql_position' => $extensionPath . 'lib/sql/class.tx_dbal_sql_position.php',
	'tx_dbal_sql_printer' => $extensionPath . 'lib/sql/class.tx_dbal_sql_printer.php',
	'tx_dbal_sql_scanner' => $extensionPath . 'lib/sql/class.tx_dbal_sql_scanner.php',
	'tx_dbal_sql_tokens' => $extensionPath . 'lib/sql/interfaces/interface.tx_dbal_sql_tokens.php',
	'tx_dbal_sql_tree_abstractexpr' => $extensionPath . 'lib/sql/tree/class.tx_dbal_sql_tree_abstractexpr.php',
	'tx_dbal_sql_tree_bad' => $extensionPath . 'lib/sql/tree/class.tx_dbal_sql_tree_bad.php',
	'tx_dbal_sql_tree_booleanprimary' => $extensionPath . 'lib/sql/tree/class.tx_dbal_sql_tree_booleanprimary.php',
	'tx_dbal_sql_tree_identifier' => $extensionPath . 'lib/sql/tree/class.tx_dbal_sql_tree_identifier.php',
	'tx_dbal_sql_tree_intliteral' => $extensionPath . 'lib/sql/tree/class.tx_dbal_sql_tree_intliteral.php',
	'tx_dbal_sql_tree_operation' => $extensionPath . 'lib/sql/tree/class.tx_dbal_sql_tree_operation.php',
	'tx_dbal_sql_tree_select' => $extensionPath . 'lib/sql/tree/class.tx_dbal_sql_tree_select.php',
	'tx_dbal_sql_tree_selectexpr' => $extensionPath . 'lib/sql/tree/class.tx_dbal_sql_tree_selectexpr.php',
	'tx_dbal_sql_tree_simpleexpr' => $extensionPath . 'lib/sql/tree/class.tx_dbal_sql_tree_simpleexpr.php',
	'tx_dbal_sql_tree_star' => $extensionPath . 'lib/sql/tree/class.tx_dbal_sql_tree_star.php',
	'tx_dbal_sql_tree_stringliteral' => $extensionPath . 'lib/sql/tree/class.tx_dbal_sql_tree_stringliteral.php',
	'tx_dbal_sql_tree_tablefactor' => $extensionPath . 'lib/sql/tree/class.tx_dbal_sql_tree_tablefactor.php',
	'tx_dbal_sql_visitor' => $extensionPath . 'lib/interfaces/interface.tx_dbal_sql_visitor.php',
	'tx_dbal_system_io_reader' => $extensionPath . 'lib/system/io/class.tx_dbal_system_io_reader.php',
	'tx_dbal_system_io_stringreader' => $extensionPath . 'lib/system/io/class.tx_dbal_system_io_stringreader.php',

	'tx_dbal_driver_pdo' => $extensionPath . 'drivers/class.tx_dbal_driver_pdo.php',
	'tx_dbal_querycache' => $extensionPath . 'lib/class.tx_dbal_querycache.php',
	'tx_dbal_sqlengine' => $extensionPath . 'lib/class.tx_dbal_sqlengine.php',
	'ux_t3lib_sqlparser' => $extensionPath . 'class.ux_t3lib_sqlparser.php',
);
?>